<MainGrid>
    cols:5

    GridLayout:
        cols:1
        size_hint_x: None
        width: root.width / 5

        Label:
            text: 'Filters'
            size_hint_y: None
            height: 40
            font_size: 30

    Label:
        size_hint_x: None
        width: 3

    Image:
        source: 'Greenish_Blue.png'

    Label:
        size_hint_x: None
        width: 3

    GridLayout:
        size_hint_x: None
        width: root.width / 3.5